modLoader="javafml" #mandatory
loaderVersion="[47,)"
modId= "armoreablemobs"
license="MIT"
[[mods]]
modId="armoreablemobs"
version="2.2.0"
displayName="Armoreable Mods"
credits="Buuz135 for making this mod"
authors="Buuz135, Witixin"
description='''
A mod that allows you to give any item to any entity when it spawns using CraftTweaker.'''
[[dependencies.armoreablemobs]]
    modId="forge"
    mandatory=true #mandatory
    versionRange="[47.1.3,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.armoreablemobs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.armoreablemobs]]
    modId = "crafttweaker"
    mandatory = true
    versionRange="[14.0.40,]"
    ordering="NONE"
    side="BOTH"
