modLoader="javafml" #mandatory
loaderVersion="[43,)"
modId= "armoreablemobs"
license="MIT"
[[mods]]
modId="armoreablemobs"
version="${file.jarVersion}"
displayName="Armoreable Mods"
credits="Buuz135 for making this mod"
authors="Buuz135, Witixin"
description='''
A mod that allows you to give any item to any entity when it spawns using CraftTweaker.
'''
[[dependencies.armoreablemobs]]
    modId="forge"
    mandatory=true #mandatory
    versionRange="[43.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.armoreablemobs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.armoreablemobs]]
    modId = "crafttweaker"
    mandatory = true
    versionRange="[10.0.14,]"
    ordering="NONE"
    side="BOTH"
